### ISSUE TITLE
Testnet

### ISSUE THREAD

**Issue by coinscrow** [BreezeHub/Breeze#23]
> dotnet run light -testnet -tumblebit -ppuri=ctb://pmkdcyilefpi2aal.onion?h=aa4e984c5655a677716539acc8cbc0ce29331429

without -testnet parameter all things running fine.

`Stratis.Bitcoin.Builder.FullNodeFeatureExecutor[0]
      An error occurred starting the application

Unhandled Exception: System.AggregateException: One or more errors occurred. (Arithmetic operation resulted in an overflow.) (Object reference not set to an instance of an object.) ---> System.OverflowException: Arithmetic operation resulted in an overflow.
   at NBitcoin.Protocol.AddressManager.LoadPeerFile(String filePath, Network expectedNetwork)
   at Stratis.Bitcoin.Base.BaseFeature.StartAddressManager() in /Users/mac/Breeze/Alpha/Stratis.Bitcoin/Base/BaseFeature.cs:line 190
   at Stratis.Bitcoin.Base.BaseFeature.Start() in /Users/mac/Breeze/Alpha/Stratis.Bitcoin/Base/BaseFeature.cs:line 135
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.<>c.<Start>b__3_1(IFullNodeFeature service) in /Users/mac/Breeze/Alpha/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 57
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean reverseOrder) in /Users/mac/Breeze/Alpha/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 102
   --- End of inner exception stack trace ---
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean reverseOrder) in /Users/mac/Breeze/Alpha/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 120
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Start() in /Users/mac/Breeze/Alpha/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 62
   at Stratis.Bitcoin.FullNode.Start() in /Users/mac/Breeze/Alpha/Stratis.Bitcoin/FullNode.cs:line 195
   at Stratis.Bitcoin.Utilities.FullNodeExtensions.Run(IFullNode node, CancellationToken cancellationToken, String shutdownMessage, String shutdownCompleteMessage) in /Users/mac/Breeze/Alpha/Stratis.Bitcoin/Utilities/FullNodeExtensions.cs:line 69
   at Stratis.Bitcoin.Utilities.FullNodeExtensions.Run(IFullNode node) in /Users/mac/Breeze/Alpha/Stratis.Bitcoin/Utilities/FullNodeExtensions.cs:line 53
   at Breeze.Daemon.Program.Main(String[] args) in /Users/mac/Breeze/Breeze/src/Breeze.Daemon/Program.cs:line 128
`

**Comment by zeptin** [comment]
This error is for an old release of the software, please download the latest release and try again.
