### ISSUE TITLE
Periodic null objref during BroadcasterJob work

### ISSUE THREAD

**Issue by carlton355** [BreezeHub/Breeze#7]
Object Reference null exception during tumbling.  Appears periodically when BroadcasterJob is doing work.

Details of exception: 

[17-09-06 19:30:20] fail: Broadcasters:   Uncaught exception BroadcasterJob : System.NullReferenceException: Object reference not set to an instance of an object.
         at Breeze.TumbleBit.Client.Services.FullNodeWalletCache.GetScriptsOf(Transaction tx) in C:\Users\carlt\source\BreezeHub\Breeze\Breeze.TumbleBit.Client\Services\FullNodeWalletCacheService.cs:line 176
         at Breeze.TumbleBit.Client.Services.FullNodeWalletCache.AddTxByScriptId(uint256 txId, FullNodeWalletEntry entry) in C:\Users\carlt\source\BreezeHub\Breeze\Breeze.TumbleBit.Client\Services\FullNodeWalletCacheService.cs:line 153
         at Breeze.TumbleBit.Client.Services.FullNodeWalletCache.ListTransactions() in C:\Users\carlt\source\BreezeHub\Breeze\Breeze.TumbleBit.Client\Services\FullNodeWalletCacheService.cs:line 239
         at Breeze.TumbleBit.Client.Services.FullNodeWalletCache.Refresh(uint256 currentBlock) in C:\Users\carlt\source\BreezeHub\Breeze\Breeze.TumbleBit.Client\Services\FullNodeWalletCacheService.cs:line 69
         at Breeze.TumbleBit.Client.Services.FullNodeBlockExplorerService.WaitBlock(uint256 currentBlock, CancellationToken cancellation) in C:\Users\carlt\source\BreezeHub\Breeze\Breeze.TumbleBit.Client\Services\FullNodeBlockExplorerService.cs:line 53
         at NTumbleBit.Services.BroadcasterJob.<>c__DisplayClass16_0.<StartCore>b__0() in C:\Users\carlt\source\BreezeHub\Breeze\BreezeCommon\BreezeProtocol\NTumbleBit\Services\BroadcasterJob.cs:line 79

**Comment by zeptin** [comment]
Fixed; Transaction member was not being populated in FullNodeWalletEntry objects
